# Generated by Django 3.2.9 on 2022-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_alter_stock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='display_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='display_volume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
