# Generated by Django 3.2.9 on 2022-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_auto_20221206_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='account',
        ),
        migrations.AddField(
            model_name='stock',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, to='stock_app.Account'),
        ),
    ]
