# Generated by Django 3.2.9 on 2022-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_auto_20221206_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='account',
            name='strategy',
        ),
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_ticker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
