# Generated by Django 3.2.9 on 2022-12-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0010_auto_20221206_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('stored_market_cap', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock_app.stock')),
            ],
        ),
    ]
