# Generated by Django 4.1.3 on 2022-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_auto_20221207_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stored_market_cap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
