# Generated by Django 4.1.3 on 2022-12-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0013_stock_stored_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=30, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stored_market_cap',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
