# Generated by Django 3.2.9 on 2022-12-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0014_alter_stock_market_cap_alter_stock_stored_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
    ]
