# Generated by Django 3.2.9 on 2022-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0015_remove_stock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True),
        ),
    ]
