# Generated by Django 3.2.9 on 2022-12-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0017_alter_stock_market_cap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketCap',
        ),
    ]
