# Generated by Django 4.1.3 on 2022-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0018_delete_marketcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_split_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
