# Generated by Django 4.1.3 on 2022-12-21 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_app', '0019_stock_stock_split_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLastSearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('min_market_cap', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('max_market_cap', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('min_volume', models.DecimalField(blank=True, decimal_places=30, max_digits=100, null=True)),
                ('date_stock', models.DateField(blank=True, null=True)),
                ('strategy', models.CharField(max_length=100)),
                ('alt_data', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
