# Generated by Django 4.1.3 on 2022-12-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0020_userslastsearchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslastsearchsettings',
            name='max_market_cap',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='userslastsearchsettings',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='userslastsearchsettings',
            name='min_market_cap',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='userslastsearchsettings',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='userslastsearchsettings',
            name='min_volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
    ]
