# Generated by Django 4.1.3 on 2022-12-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0021_alter_userslastsearchsettings_max_market_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslastsearchsettings',
            name='alt_data',
        ),
        migrations.RemoveField(
            model_name='userslastsearchsettings',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='userslastsearchsettings',
            name='strategy',
        ),
    ]
