# Generated by Django 4.1.3 on 2022-12-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0022_remove_userslastsearchsettings_alt_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslastsearchsettings',
            name='alt_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userslastsearchsettings',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
