# Generated by Django 4.1.3 on 2023-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0023_userslastsearchsettings_alt_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=6, default=100000000, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='net_gain',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
    ]
