# Generated by Django 3.2.9 on 2023-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0025_alter_stock_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker', 'date'], name='stock_app_s_ticker_53c5e8_idx'),
        ),
    ]
