# Generated by Django 3.2.9 on 2023-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0026_stock_stock_app_s_ticker_53c5e8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_sector',
            field=models.CharField(blank=True, default='NOT PROVIDED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, default='NOT PROVIDED', max_length=200, null=True),
        ),
    ]
