# Generated by Django 3.2.9 on 2023-01-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0027_auto_20230117_1617'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['stock'], name='stock_app_s_stock_i_f6525d_idx'),
        ),
    ]
