# Generated by Django 4.1.3 on 2023-01-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0028_strategy_stock_app_s_stock_i_f6525d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
