# Generated by Django 4.1.3 on 2023-01-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0029_alter_stock_high_alter_stock_low_alter_stock_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=15, default=100000000, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
