# Generated by Django 4.1.3 on 2023-01-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0030_alter_stock_high_alter_stock_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='net_gain',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
