# Generated by Django 3.2.9 on 2023-02-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0034_remove_stock_stock_app_s_ticker_53c5e8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
