# Generated by Django 3.2.9 on 2023-02-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0035_auto_20230209_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedFundRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_date', models.DateTimeField(blank=True, null=True)),
                ('interest', models.DecimalField(decimal_places=3, max_digits=5)),
                ('value', models.IntegerField(default=100)),
                ('strategy_interest', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
        ),
    ]
