# Generated by Django 3.2.9 on 2023-03-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0037_alter_fedfundrate_interest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='display_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='display_volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stored_market_cap',
        ),
    ]
