# Generated by Django 4.1.7 on 2023-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0041_userpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='background_color',
            field=models.CharField(blank=True, default='#061821', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='border_body',
            field=models.CharField(blank=True, default='black', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='button_color',
            field=models.CharField(blank=True, default='#093042', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='navbar_color',
            field=models.CharField(blank=True, default='#061821', max_length=100, null=True),
        ),
    ]
