# Generated by Django 4.1.7 on 2023-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0042_alter_userpreference_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='text_color',
            field=models.CharField(blank=True, default='white', max_length=100, null=True),
        ),
    ]
