# Generated by Django 4.1.7 on 2023-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0043_userpreference_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
