# Generated by Django 4.1.7 on 2023-04-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0044_alter_stock_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedfundrate',
            name='value',
        ),
    ]
